# templates/app-projects.yaml
{{- range .Values.teams }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-project
  namespace: argocd
spec:
  description: "Project for {{ .name }}"
  sourceRepos:
  - {{ .repoURL | quote }}
  - {{ .targetPath | quote }}
  destinations:
  - namespace: {{ .name }}-ns
    server: https://kubernetes.default.svc
  
  # roles:
  # - name: spoke
  #   policies:
  #   - p, proj:{{ .name }}-project:developer, applications, get, {{ .name }}-project/*, allow
  #   - p, proj:{{ .name }}-project:developer, applications, sync, {{ .name }}-project/*, allow
---
{{- end }}
