{{- range .Values.teams }}

{{- if .limitRange }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .name }}-default-limits
  namespace: {{ .name }}-ns
spec:
  limits:
  - type: Container
    max:
      cpu: {{ dig "limitRange" "max" "cpu" "500m" .Values | quote }}
      memory: {{ dig "limitRange" "max" "memory" "512Mi" .Values | quote }}
    min: 
      cpu: {{ dig "limitRange" "min" "cpu" "100m" .Values | quote }}
      memory: {{ dig "limitRange" "min" "memory" "128Mi" .Values | quote }}
    defaultRequest:
      cpu: {{ dig "limitRange" "defaultRequest" "cpu" "100m" .Values | quote }}
      memory: {{ dig "limitRange" "defaultRequest" "memory" "128Mi" .Values | quote }}
---
{{- end }}

{{- end }}