{{- range .Values.teams }}

{{- $lr := .limitRange | default dict -}}
{{- $max := $lr.max | default dict -}}
{{- $min := $lr.min | default dict -}}
{{- $defaultReq := $lr.defaultRequest | default dict -}}

apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .name }}-default-limits
  namespace: {{ .name }}-ns
spec:
  limits:
  - type: Container
    max:
      cpu: {{ $max.cpu | default "500m" | quote }}
      memory: {{ $max.memory | default "512Mi" | quote }}
    min: 
      cpu: {{ $min.cpu | default "100m" | quote }}
      memory: {{ $min.memory | default "128Mi" | quote }}
    defaultRequest:
      cpu: {{ $defaultReq.cpu | default "100m" | quote }}
      memory: {{ $defaultReq.memory | default "128Mi" | quote }}
---
{{- end }}