{{- range .Values.teams }}

{{- if .limitRange }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .name }}-default-limits
  namespace: {{ .name }}-ns
spec:
  limits:
  - type: Container
    max:
      cpu: {{ .limitRange.max.cpu | default "500m" | quote }}
      memory: {{ .limitRange.max.memory | default "512Mi" | quote }}
    min: 
      cpu: {{ .limitRange.min.cpu | default "100m" | quote }}
      memory: {{ .limitRange.min.memory | default "128Mi" | quote }}
    defaultRequest:
      cpu: {{ .limitRange.defaultRequest.cpu | default "100m" | quote }}
      memory: {{ .limitRange.defaultRequest.memory | default "128Mi" | quote }}
---
{{- end }}

{{- end }}