{{- range .Values.teams }}

{{- if .resourceQuota }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .name }}-resource-quota
  namespace: {{ .name }}-ns
spec:
  hard:
    pods: {{ .resourceQuota.pods | default "10" | quote }}
    requests.cpu: {{ .resourceQuota.requests.cpu | default "1" | quote }}
    requests.memory: {{ .resourceQuota.requests.memory | default "1Gi" | quote }}
    limits.cpu: {{ .resourceQuota.limits.cpu | default "2" | quote }}
    limits.memory: {{ .resourceQuota.limits.memory | default "4Gi" | quote }}
---
{{- end }}

{{- end }}