{{- range .Values.teams }}

{{- if .resourceQuota }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .name }}-resource-quota
  namespace: {{ .name }}-ns
spec:
  hard:
    pods: {{ dig "resourceQuota" "pods" "10" .Values | quote }}
    requests.cpu: {{ dig "resourceQuota" "requests" "cpu" "1" .Values | quote }}
    requests.memory: {{ dig "resourceQuota" "requests" "memory" "1Gi" .Values | quote }}
    limits.cpu: {{ dig "resourceQuota" "limits" "cpu" "2" .Values | quote }}
    limits.memory: {{ dig "resourceQuota" "limits" "memory" "4Gi" .Values | quote }}
---
{{- end }}

{{- end }}