teams:
  - name: team-one
    repoURL: 'https://github.com/leejinbok/hub-spoke-practice.git'
    targetPath: 'spokes/team-one'
    targetRevision: 'main'
    resourceQuota:
      pods: "5"
    limitRange:
      max:
        cpu: "500m"
        memory: "200Mi" # Blocks 250Mi
      min:
        cpu: "50m"
        memory: "100Mi"
      defaultRequest:
        cpu: "100m"
        memory: "150Mi"

  - name: team-two
    repoURL: 'https://github.com/leejinbok/hub-spoke-practice.git'
    targetPath: 'spokes/team-two'
    targetRevision: 'main'
    resourceQuota:
      pods: "4" # Blocks 5

  - name: team-three
    repoURL: 'https://github.com/leejinbok/hub-spoke-practice.git'
    targetPath: 'spokes/team-three'
    targetRevision: 'main'
    limitRange:
      max:
        cpu: "500m"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "200Mi" # Blocks 128Mi
      defaultRequest:
        cpu: "100m"
        memory: "300Mi"