# values.yaml
teams:
  - name: team-one
    repoURL: 'https://github.com/leejinbok/spoke-1.git'
    cpuReq: "1"
    memReq: "1Gi"
    cpuLim: "2"
    memLim: "2Gi"

  - name: team-two
    repoURL: 'https://github.com/leejinbok/spoke-2.git'
    cpuReq: "500m"
    memReq: "512Mi"
    cpuLim: "1"
    memLim: "1Gi"

  # - name: team-alpha1
  #   repoURL: 'https://gitlab.com/your-org/team-alpha-repo.git'
  #   ssoGroup: 'TeamAlpha_SSO_Group' 
  #   cpuReq: "1"
